name: "L'Agence Com'"
favicon: null
layout_spectrum: 0.5378744171466678
typography_spectrum: 0.92203
title: 'Agence de communication en Périgord Noir, Dordogne'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#575656'
    - '#f08000'
    - '#000000'
    - '#808080'
    - '#ff5500'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
