typography_spectrum: 0.94821
color:
  brandColors:
    - '#575656'
    - '#f08000'
    - '#000000'
    - '#808080'
    - '#ff5500'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5378744171466678
analytics:
  google: null
  facebook: null
  twitter: null
name: L'Agence Com'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: L'équipe
    id: 43b59922-e8c0-4430-9695-3b4f5cb6fb0a
    type: content
favicon: null
title: 'Agence de communication en Périgord Noir, Dordogne'
description: Les Professionnels de la communication en Périgord
purpose: []
